### ISSUE TITLE
Color and type styles

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#106]
**[Color Styles](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1295%3A0)**

<img width="448" alt="Screen Shot 2020-07-10 at 2 58 50 PM" src="https://user-images.githubusercontent.com/59940380/87189013-dec0b480-c2bd-11ea-9c1f-baaf6697e197.png">

**[Text Styles](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1278%3A0)**

Text styles use the FrosType typeface [FT Base](https://www.frostype.com/base) in weights Regular and Bold. This is the typeface currently used at [makerdao.com](https://makerdao.com/en/) so we'll have to tap Rich for that license (or the scope of the license will need to be upgraded).

<img width="334" alt="Screen Shot 2020-07-10 at 3 13 27 PM" src="https://user-images.githubusercontent.com/59940380/87190128-eb460c80-c2bf-11ea-94a8-66d7cd7e25a3.png">

Default transition for all hover states should be `.1s ease`.

**Comment by shea-fitz** [comment]
These styles should be mapped onto a [Dai-UI theme](https://dai-ui.now.sh/)

**Comment by MaximumCrash** [comment]
@amy-jung I can't complete this until I get the font family installed.

**Comment by MaximumCrash** [comment]
I've received the fonts and this task is no longer blocked.

**Comment by MaximumCrash** [comment]
Closed by #185
