### ISSUE TITLE
Mobile language selector - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#107]
[Language selector](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1577%3A2886)

On mobile, the default language selector rests between the breadcrumbs and the headline. It felt strange to me to have a link inside a dropdown so I moved the call for translations to be text underneath.

@MaximumCrash I realize there are currently 2 cases of language selectors: 1) default dropdown 2) emoji-flag box in the case of a page not having a locale sibling. Would it be viable to replace the flag box with a dropdown that loads placeholder text? Am I misunderstanding the issue?

![Screen Shot 2020-07-15 at 2 18 18 PM](https://user-images.githubusercontent.com/59940380/87580807-0a6ce180-c6a6-11ea-9763-46209e9585b2.png)

![Screen Shot 2020-07-15 at 2 09 39 PM](https://user-images.githubusercontent.com/59940380/87580116-fa083700-c6a4-11ea-9622-2b907256505e.png)

**Comment by MaximumCrash** [comment]
@shea-fitz let me know when this has been decided.

**Comment by MaximumCrash** [comment]
@shea-fitz in regards to your question, my understanding is the flag emoji case is a call to action for folks to translate a page that doesn't have any other languages, but to make aware what languages the site already supports. So while I'm not the biggest fan of the country flags because they don't 100% visually communicate "locale", I'd say a placeholder dropdown may be more confusing.  @twblack88 @amy-jung thoughts?

**Comment by amy-jung** [comment]
hmm @MaximumCrash can you describe that a bit more? What is the reason a placeholder dropdown may be more confusing? 

Also, I understand common practice is putting language selector to be in the header or footer as a dropdown. What is the design decision around putting it aligned with the breadcrumb instead?

Also something to consider: Is it the CTA for folks to translate the page that is throwing us off? If so, we can consider adding a new emoji or icon that signifies the CTA for 'translate into your language' and it clicking it would take you to the translations page

I did a quick search around best practices and gathered some heuristics:
1. **Language Button in header, but separate page for language directory + CTA:** [Ethereum.org](https://ethereum.org/en/languages/) and [React](https://reactjs.org/languages) put languages aligned with the header and link to a separate page for a CTA where you can choose/help with language specific details.
2. **Basic Text Dropdown: (often in footer)** Ubuntu Community
3. **Emoji with current selection and small card selector with options opens:** I agree country flags emoji aren't the most communicative, but if we do, we should add text (ie. Stripe example & also seen in IDEO, although these websites don't have a CTA)
<img width="1012" alt="Screen Shot 2020-07-16 at 11 00 33 AM" src="https://user-images.githubusercontent.com/26228406/87651803-ab65a600-c753-11ea-91cd-42d4eb9f4813.png">
4. **Text with full text only card dropdown** (Electron:)
<img width="1330" alt="Screen Shot 2020-07-16 at 11 46 50 AM" src="https://user-images.githubusercontent.com/26228406/87656700-1e721b00-c75a-11ea-86a8-48a8a5f0cf09.png">

## **Side note** 
@twblack88 we should change the CTA to "Request a translation" as it's a more direct CTA than expecting someone to join a team to request something. Then adding a CTA in the translations page.

**Comment by twblack88** [comment]
Agree on changing the infotext/CTA. Request a translation is far better. 

A dropdown is cleaner IMHO.

**Comment by MaximumCrash** [comment]
Closed by #217
