### ISSUE TITLE
Tout cards - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#108]
[Touts
](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1350%3A0)

On desktop, touts can be displayed in two-column or one-column layouts. If there is only one tout, it should default to single-column (the width of the content container). Mobile touts are all single-column.

![Screen Shot 2020-07-13 at 5 15 50 PM](https://user-images.githubusercontent.com/59940380/87354461-91964a00-c52c-11ea-9507-00826efe9a81.png)

**Comment by MaximumCrash** [comment]
Closed by #219
