### ISSUE TITLE
Process stepper - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#109]
[Process stepper](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1535%3A31)

On desktop, numbers should appear inline with content, but on mobile, numbers should stack above content, remaining left aligned.

![Screen Shot 2020-07-13 at 4 01 00 PM](https://user-images.githubusercontent.com/59940380/87348013-116ae700-c522-11ea-881f-11824d521e4a.png)

**Comment by MaximumCrash** [comment]
Closed by #219
