### ISSUE TITLE
Headers/footers - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#110]
[Headers](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1309%3A58)

More detailed mobile specifications illustrated [here.](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1170%3A344)

![Screen Shot 2020-07-15 at 12 04 32 PM](https://user-images.githubusercontent.com/59940380/87568241-595d4b80-c693-11ea-9f7f-0b1c3932f057.png)

![Screen Shot 2020-07-15 at 12 04 48 PM](https://user-images.githubusercontent.com/59940380/87568261-62e6b380-c693-11ea-8d10-fe32ccaa9eb1.png)

![Screen Shot 2020-07-15 at 12 08 19 PM](https://user-images.githubusercontent.com/59940380/87568587-e30d1900-c693-11ea-9ec9-12a2c52ebb93.png)

Footers pending larger conversation.

**Comment by MaximumCrash** [comment]
This is a question for @twblack88 and @amy-jung

**Comment by MaximumCrash** [comment]
@shea-fitz I'll also need the Maker logo SVG you're using in your footer spec.

**Comment by amy-jung** [comment]
I think this requires some more thinking around where users are coming from/where they should go to leave. Some ideas (not saying it should be written or sectioned like this in the footer):

**Comm-Dev Specific:** 
1. Resources/formerly "Develop" page
2. AwesomeMakerDAO

**Socials:**
Forum, Github Repo, Community chat, Youtube channel, reddit

Things I'm not sure about:
- Privacy Policy
- keeping all from "Products": Oasis, Migrate, Ecosystem, Governance?
- MakerDAO/Foundation specific stuff: 1. Whitepaper 2. Maker Docs 3. MakerDAO.com

**Comment by amy-jung** [comment]
> @shea-fitz I'll also need the Maker logo SVG you're using in your footer spec.

If it's the original
https://www.notion.so/makerdao/Maker-Brand-ac517c82ff9a43089d0db5bb2ee045a4

**Comment by shea-fitz** [comment]
Also here in white if easier:

[Logo_Maker_White.svg.zip](https://github.com/makerdao/community-portal/files/4925553/Logo_Maker_White.svg.zip)

**Comment by MaximumCrash** [comment]
Closed by #199
