### ISSUE TITLE
Callouts - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#111]
[Callouts](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1538%3A156)

<img width="888" alt="Screen Shot 2020-07-22 at 10 34 41 AM" src="https://user-images.githubusercontent.com/59940380/88189338-f4f83a00-cc06-11ea-9557-8036aa9d9856.png">

**Comment by MaximumCrash** [comment]
@shea-fitz Has anything changed for this?

**Comment by shea-fitz** [comment]
> @shea-fitz Has anything changed for this?

Very few changes

**Comment by twblack88** [comment]
looks like: icon styling and rounded borders?

**Comment by isaacpearl** [comment]
@MaximumCrash Mind if I take this one?

**Comment by MaximumCrash** [comment]
@isaacpearl as soon as #112 is completed you're clear to start this one. If I catch up I'll take it.

**Comment by MaximumCrash** [comment]
@isaacpearl I've caught up. I'll take this off your hands.

**Comment by MaximumCrash** [comment]
Closed by #244
