### ISSUE TITLE
Buttons - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#112]
[Buttons](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1311%3A0)

<img width="771" alt="Screen Shot 2020-07-10 at 5 37 59 PM" src="https://user-images.githubusercontent.com/59940380/87204986-4e419e80-c2d4-11ea-8b68-a2eae8423600.png">

Default transition for all hover states should be `.1s ease`.

**Comment by isaacpearl** [comment]
- [ ] Add Small variant

**Comment by isaacpearl** [comment]
- [x] add ```small``` variant parsing to ```Button.js```
- [x] move styles to ```theme-ui.js```
- [x] add new ```primary``` styling
- [x] add new ```secondary``` styling
- [x] add new ```outline``` styling
- [x] add new ```small``` styling
- [x] add ```disabled``` styling to all
- [x] fix link styling for all
- [x] double check all css from figma
- [x] get info about dark mode style change handling (add new colors to dark mode object? catch change in variant style?)

PR Notes:
- [x] styles moved into ```theme-ui.js``` vs inline
- [x] change to Button composition (link parent vs using ```as={Link}```)
- [x] update cheat sheet with ```small``` prop, remove language about combining outline + secondary

**Comment by isaacpearl** [comment]
@shea-fitz Should buttons containing external links display an arrow icon svg to the right of their text like they did before?

**Comment by shea-fitz** [comment]
@isaacpearl Icons within buttons should be left-aligned as shown

![Screen Shot 2020-07-20 at 9 49 01 AM](https://user-images.githubusercontent.com/59940380/87945113-4a4d1380-ca6e-11ea-9571-221b136c2ce7.png)

**Comment by MaximumCrash** [comment]
Closed by #222
