### ISSUE TITLE
2-column comparison - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#113]
[2-column comparison](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1535%3A0)

On desktop, columns should display inline and be equal heights. On mobile, columns should stack and each be the height of their respective content.

![Screen Shot 2020-07-13 at 10 59 31 AM](https://user-images.githubusercontent.com/59940380/87319676-eec3d880-c4f7-11ea-97a9-cc56ac3c1fdf.png)

**Comment by MaximumCrash** [comment]
Closed by #250
