### ISSUE TITLE
3-column chocolate box - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#114]
[Chocolate box](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1577%3A1753)

In lieu of text and emojis, I've shown a series of examples with different combinations of text, headlines, and images (one use case for images + text being, e.g. a gallery of blog posts)

![Screen Shot 2020-07-16 at 11 07 37 AM](https://user-images.githubusercontent.com/59940380/87688119-90dffc80-c754-11ea-8492-faf3e6fd6865.png)

**Comment by MaximumCrash** [comment]
@shea-fitz Has anything for this changed?

**Comment by shea-fitz** [comment]
> @shea-fitz Has anything for this changed?

pending changes

**Comment by shea-fitz** [comment]
These specs have absorbed what was FKA Categories (#120 ). There is no longer a need for separate chocolate box and category components.

**Comment by MaximumCrash** [comment]
@twblack88 Categories has been closed in favor of this component. The existing Chocolate Box component better fits the needs of this spec than Categories.

**Comment by MaximumCrash** [comment]
Closed by #219
