### ISSUE TITLE
Lists - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#115]
[Lists](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1349%3A0)

List rows should only have a hover state if the row contains a link. Default transition for all hover states should be `.1s ease`.

<img width="1299" alt="Screen Shot 2020-07-17 at 11 32 19 AM" src="https://user-images.githubusercontent.com/59940380/87803943-2fd22a80-c821-11ea-843b-67334ac055fa.png">

**Comment by MaximumCrash** [comment]
Closed by #199
