### ISSUE TITLE
Status alerts/banners - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#116]
[Status banners
](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1568%3A615)

Users should be able to dismiss status banners by way of a "close" icon that is top-right aligned inside the banner.

![Screen Shot 2020-07-14 at 2 14 17 PM](https://user-images.githubusercontent.com/59940380/87461526-9286b480-c5dc-11ea-8acb-43187986d762.png)

**Comment by MaximumCrash** [comment]
@shea-fitz Status banners are not notification banners. These are banners that can show up anywhere in a page. I'm not sure them being dismissable meets their expected use by the team. 

@twblack88 @amy-jung Any thoughts?

**Comment by amy-jung** [comment]
Yes, @MaximumCrash you're correct. They are indicating "status" of the page/program, therefore static and not dismissible. I'm struggling to think of other ways we would need a notification type banner but can't think of one - @twblack88 any come to mind?

Note on the design @shea-fitz - can we maximize impact of the status by having the entire banner a single color (yellow) for warning or (green/blue) for success? It'd be easier to understand at a glance.

**Comment by shea-fitz** [comment]
@MaximumCrash @amy-jung understood - solid-color static banners [here](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1568%3A615) and below:

![Screen Shot 2020-07-15 at 9 33 41 AM](https://user-images.githubusercontent.com/59940380/87551394-47bd7900-c67e-11ea-8018-5852f9cc4a7d.png)

**Comment by MaximumCrash** [comment]
Closed by #217
