### ISSUE TITLE
Breadcrumbs - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#117]
[Breadcrumbs](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1597%3A3865)

The text of each breadcrumb should behave like a link with no underline, with the exception of breadcrumbs replaced by an ellipse, which shouldn't be clickable.

![Screen Shot 2020-07-14 at 11 03 21 AM](https://user-images.githubusercontent.com/59940380/87441895-a2dd6600-c5c1-11ea-8811-46a0afb5dd77.png)
![Screen Shot 2020-07-14 at 11 03 28 AM](https://user-images.githubusercontent.com/59940380/87441908-a7098380-c5c1-11ea-8f0a-7248125008a3.png)
![Screen Shot 2020-07-14 at 11 03 38 AM](https://user-images.githubusercontent.com/59940380/87441928-ac66ce00-c5c1-11ea-9770-854b619b2031.png)

**Comment by MaximumCrash** [comment]
Closed by #217
