### ISSUE TITLE
Create missing icons

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#118]
[Icons](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1577%3A2825)

- [x] Minus
- [x] Sun
- [x] Moon
- [x] Lightbulb

![Screen Shot 2020-07-14 at 6 03 21 PM](https://user-images.githubusercontent.com/59940380/87480919-506d6b00-c5fc-11ea-85f7-38f982d556fd.png)

**Comment by MaximumCrash** [comment]
@shea-fitz can I get these as SVGs please.

**Comment by shea-fitz** [comment]
[comm-dev_icons.zip](https://github.com/makerdao/community-portal/files/4925447/comm-dev_icons.zip)

**Comment by shea-fitz** [comment]
Update, please use this solid version of the lightbulb icon which is...more recognizably a lightbulb in practice
[lightbulb.svg.zip](https://github.com/makerdao/community-portal/files/4925644/lightbulb.svg.zip)

**Comment by MaximumCrash** [comment]
Closed by #185
