### ISSUE TITLE
Accordions - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#119]
[Accordions](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1568%3A603)

![Screen Shot 2020-07-13 at 4 12 23 PM](https://user-images.githubusercontent.com/59940380/87349021-b1754000-c523-11ea-8a03-e621a6f56a25.png)

**Comment by MaximumCrash** [comment]
Closed by #209

**Comment by MaximumCrash** [comment]
I will be applying the mobile styles of this in my PR wipe of components.
