### ISSUE TITLE
Component - Links

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#12]
For links to content and navigational links in the portal. Also [overview of visual treatments of links. ](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#f2a62f15c0204e27b42286b9ac9fab83)

- [x] Regular links e.g. all the [green links on this frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A3046) would be navigational 
- [x] Platform Callout link e.g. the [rocketchat icon](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3e92593f-aee7-47d5-9157-0eafb92509fb%2FUntitled.png?table=block&id=5af6e554-f7e9-42c0-9df5-5db01e8197e1&width=2730&cache=v2)

**Comment by MaximumCrash** [comment]
@isaacpearl Best practice for this would be:
- There's already a Link component I made, expand upon it to support icons. 
- If you need to change the style of our anchor links then you'll want to edit our theme file in src/gatsby-plugin-theme-ui/index. Refer to the theme-ui docs on how to edit anchor link styles. 

Composition expections:

1. Normal MDX links should render as the Regular links mentioned above. 
They're already leveraging the Link component I created (see src/modules/shortcodes).
```jsx
[Forum](https://forum.makerdao.com/)
```

2. Explicitly render using component syntax. (This is the case for icons)
(I would recommend finding a way to add the rocket chat icon, into the icons object in our custom theme file)
```jsx
<Link to={"/en/whatever"} icon={[insert icon from package or emoji]}> 
   Whatever
</Link>
```

**Comment by MaximumCrash** [comment]
@isaacpearl has completed this.
