### ISSUE TITLE
Categories - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#120]
[View component](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73)

<img width="750" alt="Screen Shot 2020-07-08 at 10 47 11 AM" src="https://user-images.githubusercontent.com/59940380/86933335-6f559400-c108-11ea-8db9-d252fcd01b97.png">

**Comment by MaximumCrash** [comment]
@shea-fitz has anything changed for this?

**Comment by shea-fitz** [comment]
> @shea-fitz has anything changed for this?

pending changes

**Comment by shea-fitz** [comment]
@MaximumCrash @twblack88 @amy-jung This component feels redundant upon expanding on chocolate box variations in #114 . Thoughts? Should there be a clearer delineation between #114 and this component, or should they be treated more as one component with variants?

**Comment by amy-jung** [comment]
From what I've read in Ryan's original doc, I don't see a difference in how content would differ. I agree with you that the chocolate box variation will suffice.

**Comment by MaximumCrash** [comment]
I will close this Issue since Categories is no longer a component based on the discussion above. I will remove it from our shortcodes, but leave the existing component in code if some day someone wants this exact spec.
