### ISSUE TITLE
Info blocks - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#121]
[Info blocks (image + text)](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1582%3A0)

These should be for home/landing page use only. Grey squares pictured are stand-ins for images.

![Screen Shot 2020-07-14 at 2 54 23 PM](https://user-images.githubusercontent.com/59940380/87464918-e8aa2680-c5e1-11ea-8a37-4b0afdb6d10e.png)

**Comment by shea-fitz** [comment]
Tweaked these a tad to make the spacing cleaner/clearer

**Comment by MaximumCrash** [comment]
Closed by #219
