### ISSUE TITLE
Tabs - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#122]
Keeping this component around had a ? on it last I heard.  

[View component](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#d6ddfe8ccace425bb63853494eac2fd6)

<img width="733" alt="Screen Shot 2020-07-08 at 11 45 52 AM" src="https://user-images.githubusercontent.com/59940380/86940328-ab8cf280-c110-11ea-8e53-af47b08f4702.png">

**Comment by MaximumCrash** [comment]
@twblack88 can talk more about this, but at the moment this looks like a heavy no.

**Comment by twblack88** [comment]
Agree on deprioritizing tabs. Seems like two columns can fit the use case fine, and we have mobile styling for those columns too.

**Comment by MaximumCrash** [comment]
@twblack88 since we won't be implementing this component at all (as they weren't included in the new design specs by @shea-fitz) I'll be closing this issue.
