### ISSUE TITLE
Image and video components

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#123]
Additional considerations include audio embeds (Soundcloud?), multi-video (playlists?)

[View component
](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A0)

<img width="671" alt="Screen Shot 2020-07-08 at 11 53 35 AM" src="https://user-images.githubusercontent.com/59940380/86941187-a9776380-c111-11ea-8df8-60e7859f2555.png">

**Comment by MaximumCrash** [comment]
@shea-fitz Please see my PR about this component https://github.com/makerdao/community-portal/pull/55

**Comment by MaximumCrash** [comment]
As for additional embeds, that what this issue #92 is asking for. 

With the time we have left @amy-jung, #92 is starting to look more like a v2 nice to have.

**Comment by amy-jung** [comment]
ok not too worried about that
