### ISSUE TITLE
Lists not working correctly

### ISSUE THREAD

**Issue by andytudhope** [makerdao/community-portal#125]
There are still some residual issues with lists:

There are two separate failures in this respect.

1. Subcontent renders as it's own list item, not smaller, grey text below the main child. Maybe I am structuring this wrongly?
 2. Arrows are right next to links, not big and at the end of the list item as in the designs. These issues can be found on the guide-to-hacking page.

If I use the Lists as documented and add a `-` for each child in the list component, this issue becomes even worse and an empty child renders above either list item as in the following screenshot from the snippet below:

```
<List>
- <Link to="https://github.com/makerdao/dai-ui">Dai UI</Link>
    - Components and React-based recipes for various themes

</List> 
```

![Screenshot from 2020-07-08 19-50-29](https://user-images.githubusercontent.com/13001517/86960171-6e038600-c15f-11ea-81bf-0ddbfe8a1eb7.png)

**Comment by MaximumCrash** [comment]
Fixed by #133
