### ISSUE TITLE
Component- Tabs

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#13]
Manage page length by allowing the user to choose the type of content they're interested in via Tabs. Avoids needing to display all content by default. 

[Figma Explainer](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev)

[clarifier on notion](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#d6ddfe8ccace425bb63853494eac2fd6)

**Comment by as-dr** [comment]
@MaximumCrash My implementation for the [Transparency Dashboard](https://grants.makerdao.com) uses a container with `white-space` set to `nowrap` (so it doesn't wrap to a second line) and then `overflow: scroll`. 

I do agree with you that I'm not sure if tabs are really the best way to be breaking up the page content here. I think my implementation in the Transparency Dashboard (to display grantee projects by category) is valid, as it seeks to allow the user to filter a list of total results to partial ones. 

But to break up a page with tabs seems dangerous as it can reduce information scent and impede discoverability. 

I really think this component should be discussed more and considered in the context of possible alternatives. 

I do agree that progressive disclosure is important, but a simpler way to achieve it is just to break things out into more pages, OR have collapsible content sections (that are collapsed by default) within a single page that users can then expand as desired.

**Comment by MaximumCrash** [comment]
@twblack88 I'm going to close this
