### ISSUE TITLE
Component- Buttons

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#14]
[Figma frame with color and button styles ](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A288)

**Comment by MaximumCrash** [comment]
@isaacpearl 

This one is pretty straight forward. Use the ThemeUI Button. If there are certain styles missing implement them into our theme file index.js file. 

I imagine that most if not all buttons on our site will actually be links to other pages. This means you can most likely make a Button component that actually implements the Link component. 

Composition Example:

Default
```jsx
<Button to={"/en/whatever"}>
Button Text
</Button>
```


Secondary
```jsx
<Button secondary to={"/en/whatever"}>
Button Text
</Button>
```

Outline 
NOTE: Support outline styles for both primary button and secondary style. 
```jsx
<Button outline to={"/en/whatever"}>
Button Text
</Button>

<Button secondary outline to={"/en/whatever"}>
Button Text
</Button>
```

**Comment by MaximumCrash** [comment]
After some tweaks, I can confirm this is completed.
