### ISSUE TITLE
Component - Callout

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#15]
Inspired by a couple platforms this allows for a break in content while highlighting crucial information. 

[Figma frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A1154)

**Comment by MaximumCrash** [comment]
@isaacpearl Best practices for this would be to:
- Use Theme ui for all of it. 
- Have it's composition support any icon
- Have it's composition support 2 styles (version1 default, version2 "secondary")
- Children of component should support all types of markdown

For example of how I would expect it to be written in MDX:

Composition Example A (default)
```jsx
<Callout>
## Heading 2

This is just an example of MDX as children of this callout. Make use of the MDXRenderer component. 
</Callout>
```

Composition Example B (with enum Icon props and secondary type)
```jsx
<Callout warning secondary>
### MDX

This is example MDX. 

!(image.png)[./images/image.png]
</Callout>
```

Composition Example C (with custom Icon)
```jsx
<Callout icon="[insert emoji or icon from Maker icons]">
Some more MDX
</Callout>
```

**Comment by isaacpearl** [comment]
Which icons should be supported automatically (example B) vs specific assignments (example C)?

**Comment by MaximumCrash** [comment]
This has been completed in #37
