### ISSUE TITLE
Code snippets - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#152]
[Code snippet](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1577%3A1635)

This should use the system default monospace.

![Screen Shot 2020-07-13 at 5 50 06 PM](https://user-images.githubusercontent.com/59940380/87357098-4f233c00-c531-11ea-8f87-ce3f167d2641.png)

**Comment by MaximumCrash** [comment]
@shea-fitz just so you're aware our code rendering engine Prism will automatically highlight pieces of text it recognizes as variables or strings, ect. I'll be able to meet your needs for non-highlighted codeblocks, but just something I thought you'd want to know.

**Comment by MaximumCrash** [comment]
Closed by #199
