### ISSUE TITLE
Component - Status Banner

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#16]
A component to communicate a status about something like an initiative. If possible, including parameters for page justification would be really helpful. Like sticky-ing to the top or following on scroll. 

[Figma Frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A728)

**Comment by MaximumCrash** [comment]
@isaacpearl This one is complex in that it includes 2 types that have different scrolling functionality. 

Version 1:
This should not stick, and can be used in content as normal
NOTE: Default should be the maker-teal color.
```jsx
<Status>
## MDX Content should be able to go inside of this. 
</Status>

<Status warning>
This is a warning status, it's tab should be the yellow color in our theme.
</Status>

<Status error>
This is an "error" looking status. It's tab should be the red color provided for our theme. 
If none is provided. Ask. 
</Status>

<Status color="#FFFFFF">
User should be able to define custom status color as well.
**NOTE: I will integrate a W3 contrast checker for automatically changing the color of the text based on it's background for best readability. Let me know when you get to this part.** 
</Status>
```

Version 2:
This status banner is included in MDX as expected, however it's functionality should be sticky (as in when I scroll past it, it should stay at the top of the page). 

NOTE: This functionality is difficult to get right. If you want me to pick it up let me know asap. 

```jsx
<Status sticky>
Background color of these follow the same principles
</Status>

<Status sticky warning>
Background color of these follow the same principles
</Status>

<Status sticky error>
Background color of these follow the same principles
</Status>

<Status sticky color="#FFFFFF">
User should be able to define custom status color as well
</Status>
```

**Comment by isaacpearl** [comment]
@MaximumCrash I see what you mean about the complexity here - I think it might be better if you're down to take this one while I tackle the simpler components.

**Comment by MaximumCrash** [comment]
This has been completed by #39
