### ISSUE TITLE
Dark mode toggle - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#161]
[Dark mode toggle](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1597%3A4829)

As it stands I only include the mode toggles on mobile in the "main menu display" (to avoid them getting lost in longer scrolls on submenu pages...I suppose they could go above nav items, but don't think they need that prioritization).

![Screen Shot 2020-07-15 at 11 41 50 AM](https://user-images.githubusercontent.com/59940380/87565843-2d8c9680-c690-11ea-863a-26889d947381.png)
![Screen Shot 2020-07-15 at 11 42 06 AM](https://user-images.githubusercontent.com/59940380/87565870-3715fe80-c690-11ea-9bfd-62254802737c.png)

**Comment by shea-fitz** [comment]
@all-contributors please add @shea-fitz for design

**Comment by MaximumCrash** [comment]
Closed by #199
