### ISSUE TITLE
Tables - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#163]
[Tables](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1368%3A81)

Very simple styling in regards to #101 . I'm wary of zebra stripes from a UX perspective because it runs the risk of positing false significance on highlighted cells. Adding additional padding in cells seeks to increase legibility as zebra stripes intend to. 

![Screen Shot 2020-07-14 at 11 10 57 AM](https://user-images.githubusercontent.com/59940380/87443153-1c298880-c5c3-11ea-92b2-e58529c72ed1.png)

**Comment by MaximumCrash** [comment]
Closed by #193
