### ISSUE TITLE
Components - Touts

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#17]
**Use when you want to give a link extra visual prominence. These are primarily used to suggest next steps for users or promote a business objective.**

[Ryan's explainer](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413) has two options: card and stroke. 

- [ ] [Card types](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A180) 
- [ ] [Stroke method](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#90962e67666640d9835f311fa6144760)

**Comment by twblack88** [comment]
For dev, the best value for coding is the card types but we might uncover use for the border stroke.

**Comment by MaximumCrash** [comment]
Closed by #51
