### ISSUE TITLE
Home page - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#204]
[Home ](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=2101%3A422) is complete with images. @amy-jung @twblack88 how is content doing on this page?

![Screen Shot 2020-07-25 at 10 05 44 PM](https://user-images.githubusercontent.com/59940380/88469800-ffdef300-cec2-11ea-8498-51664638aa67.png)

![Screen Shot 2020-07-25 at 10 01 24 PM](https://user-images.githubusercontent.com/59940380/88469732-6283bf00-cec2-11ea-8df5-236869c6770c.png)

**Comment by twblack88** [comment]
all done and staged.
