### ISSUE TITLE
Component - Process Stepper

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#21]
This might need it's own template with some fancy shortcode options or even yaml presets. 

[Figma frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A539)

**Comment by twblack88** [comment]
More on the YAML idea, where you can feed to the number of process steps in the header and the MDX file renders a process stepper of however many we choose. Probably wrong but an idea i'd like to explore something akin to this:
` --- `
` title: CDIP process page `
` process count : 4 `
` --- `

**Comment by MaximumCrash** [comment]
This is completed by #46
