### ISSUE TITLE
Landing pages - Visual design

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#218]
@amy-jung @twblack88 where does content stand for these (/work-with-us, /funding, /learn)? For the time being I'm going off of roughly what is in Ryan's old [Figma.](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=255%3A388)

**Comment by amy-jung** [comment]
Work With Us: https://hackmd.io/@YemuuYMVQlulHcUUJJLS9g/HkxTftv6U (I can see that you got started on this for the Figma)

Funding: https://hackmd.io/MMMew4GARTOvRnNXkV0hZA

Working on Learn

**Comment by shea-fitz** [comment]
[Work with us](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=2000%3A5975) is complete with images and content.

![Screen Shot 2020-07-25 at 9 58 41 PM](https://user-images.githubusercontent.com/59940380/88469673-091b9000-cec2-11ea-8462-da43201fc2b1.png)

**Comment by shea-fitz** [comment]
[Funding](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=1951%3A1) is complete with images and content (with the exception of specific values for stats).

![Screen Shot 2020-07-25 at 9 59 53 PM](https://user-images.githubusercontent.com/59940380/88469698-2cded600-cec2-11ea-95a5-5d56dd48668c.png)
