### ISSUE TITLE
Image assets

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#224]
Includes illustrations from Richard, icons for chocolate boxes on landing pages (or smaller, isolated illustrations if we can get them)

**Comment by MaximumCrash** [comment]
When it's time to add this to the the content area I recommend putting them in the static/images directory.

**Comment by shea-fitz** [comment]
@MaximumCrash would you kindly grant me push access so I can upload files directly?

**Comment by MaximumCrash** [comment]
@shea-fitz unfortunately that's out of my hands. @twblack88 is an admin afaik he can add you as a contributor.

**Comment by twblack88** [comment]
Gotchu

**Comment by shea-fitz** [comment]
Have been clumsily navigating git/PR's while simply trying to delete + re-upload so I'm just going to leave these here (all necessary illustrations for home + landing pages)

[illustrations.zip](https://github.com/makerdao/community-portal/files/4977029/illustrations.zip)

**Comment by twblack88** [comment]
Uploaded today #288
