### ISSUE TITLE
Component - Accordian

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#24]
Collapsible information nested underneath a question or prompt for more information. See [figma here](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A1477) at the bottom under `more information`. 

This component allows FAQs to be presented on pages relevant to the questions without cluttering the page. And means we shouldn't need to have large pages of FAQs separate from other content. [More of Ryan's explanation if needed](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#709deea1f6c7456881466c7b4bf66603)

**Comment by MaximumCrash** [comment]
Completed by #47
