### ISSUE TITLE
V2 - Visual design issues and inconsistencies

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#265]
Collective notes of inconsistencies between implementation and mock-up or other layout issues, as seen in #199 and #219 to be addressed in v2.

**Links in light mode**
Some links appear light green, which doesn't pass accessibility standards. Links in Light mode are differentiated from other text in weight and underline, but not color.
<img width="1054" alt="Screen Shot 2020-07-28 at 12 27 13 PM" src="https://user-images.githubusercontent.com/59940380/88728590-1920b300-d100-11ea-8d01-6f003b180587.png">

**Body text**
In both light and dark modes, body and header text use the color code `text`. (as each other in their respective themes). Body text should use `textMuted`.
<img width="1062" alt="Screen Shot 2020-07-28 at 12 31 24 PM" src="https://user-images.githubusercontent.com/59940380/88728710-4f5e3280-d100-11ea-8888-d903933760d2.png">
![Screen Shot 2020-07-28 at 6 33 35 PM](https://user-images.githubusercontent.com/59940380/88728983-d9a69680-d100-11ea-9940-df6abb9cf124.png)
![Screen Shot 2020-07-28 at 6 33 22 PM](https://user-images.githubusercontent.com/59940380/88728972-d27f8880-d100-11ea-9f16-80fa10445ea4.png)

**Content container**
Currently, page content in-line with the language selector has a max width. This max-width should be applied to all main page content for easier readability/more centered content (so basically, the desktop language selector should be in its own column)
<img width="1424" alt="Screen Shot 2020-07-29 at 12 03 28 PM" src="https://user-images.githubusercontent.com/59940380/88824144-f5a74800-d193-11ea-99a3-b8486745db46.png">

**Code snippet font weight**
Font weight for code snippets should be 400 (pictured below the font weight is 600).
<img width="488" alt="Screen Shot 2020-07-29 at 12 13 51 PM" src="https://user-images.githubusercontent.com/59940380/88825034-115f1e00-d195-11ea-9920-df67f79f10f1.png">

**Comment by MaximumCrash** [comment]
@twblack88 @shea-fitz I'm going to try to squeeze this in for V1 since I think it's really important for marketing that these things are done asap.

**Comment by MaximumCrash** [comment]
Closed by #474
