### ISSUE TITLE
Component- Inline Image Support 

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#27]
Might be done already in #5 but just in case the [CDIP image in this frame](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A2608) is a good example.

**Comment by MaximumCrash** [comment]
This has been implemented in the same way you'd add images here on github or any other Markdown application. 

However there's 2 ways you can do it. You can use a locally added file (files add to the images directory of the content folder)

```![starfox](../images/starfox.png)```
![starfox](https://user-images.githubusercontent.com/9157341/84380657-b4dc7b00-abb5-11ea-88b7-d9d61ec1bffa.png)


or you can add files that exist on the web. 
```![placekitten](https://placekitten.com/g/200/300)``` (this would be a picture of a kitten)
![Screen Shot 2020-06-11 at 7 35 46 AM](https://user-images.githubusercontent.com/9157341/84380923-33391d00-abb6-11ea-8f35-4ed49be4207f.png)
