### ISSUE TITLE
Feature- side nav toggle doesn't close 

### ISSUE THREAD

**Issue by annaalexakr** [makerdao/community-portal#277]
Expected behavior: clicking on the side navigation menu once to expand the menu. click one more time to collapse the menu - toggle between open and close by clicking on the chevron

Actual behavior: clicking once opens the menu, clicking again doesn't collapse it. There's no way to collapse the menu besides opening another subtopic menu

![Screen Shot 2020-07-31 at 5 48 31 PM](https://user-images.githubusercontent.com/68355495/89086165-0b189f80-d357-11ea-9e26-308094995fdd.png)

@twblack88 
@befitsandpiper

**Comment by MaximumCrash** [comment]
@amy-jung @twblack88 This isn't a bug. Before I tackle this I would like a design spec on how we would expect the sidenav to work from a usage standpoint.

**Comment by twblack88** [comment]
A cool mental model of this I guess is that it's like finder in a mac. Does that sound right @annaalexakr

**Comment by MaximumCrash** [comment]
Closed by #441
