### ISSUE TITLE
Component- Inline Video(s)

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#28]
The [governance page](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A1833) will see the most use of inline video. There are also a few options 

- [ ] CTA linkout, `button` with inline text that takes you to a video
- [ ] v2 with embed 
- [ ] v3 main video embed with carousel

**Comment by as-dr** [comment]
@MaximumCrash This one's a little more complicated, since I assume we're going to be embedding 3rd party video content from places like YouTube? 

This is an excellent, comprehensive resource for how to tackle it: https://css-tricks.com/fluid-width-video/

**Comment by MaximumCrash** [comment]
@as-dr Ah I should have clarified. The width is the easy part of solving for mobile. The question is how to best handle the versions that include carousels.

**Comment by MaximumCrash** [comment]
From call: to be revisited later in sprint once content reaches a point for needs on video. 
Wait to hear from David on his thoughts.

**Comment by MaximumCrash** [comment]
Closed by #55
