### ISSUE TITLE
Content crossed over side navigation menu 

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community-portal#281]
This is in the [staging site link](https://community-portal-staging.makerfoundation.com/)

Expected Behavior: Content holds parallel to side navigation panel

Existing Behavior: Content overlaps side navigation panel

Strange note: I only happened once, so not sure if it's a real bug or if it is one time

<img width="1439" alt="Screen Shot 2020-08-02 at 11 18 49 PM" src="https://user-images.githubusercontent.com/26228406/89132750-b0c63d00-d516-11ea-9c7f-2525e67ba452.png">
<img width="1394" alt="Screen Shot 2020-08-02 at 11 18 34 PM" src="https://user-images.githubusercontent.com/26228406/89132752-b3c12d80-d516-11ea-9c9e-8884746f4bda.png">

**Comment by amy-jung** [comment]
happened again, but now the component is pushing past the side navigation line

<img width="972" alt="Screen Shot 2020-08-05 at 5 47 17 PM" src="https://user-images.githubusercontent.com/26228406/89434535-eef47400-d743-11ea-8cbd-948b2e1589a7.png">

**Comment by twblack88** [comment]
It's a `category` not a `chocolate`! That's why. 😄 

I pushed changes to staging yesterday and the funding page is still wonky. But it's also wonky on local builds. That visual polish is on the roadmap to fix for 8/13 as people move from just getting basic pages up to making them look really nice.

**Comment by twblack88** [comment]
![Screen Shot 2020-08-05 at 10 34 12 AM](https://user-images.githubusercontent.com/8991325/89444866-3c062500-d707-11ea-9403-4b8b33734a62.png)
Pushed updates so it at least doesn't look **_as_** janky

**Comment by scottrepreneur** [comment]
I'm also getting this in Chrome on Mac. Not on Brave or Safari however.

**Comment by HaydenSander** [comment]
Also seeing the same issue on Windows.

Chrome:
![image](https://user-images.githubusercontent.com/39495762/89458645-3535dd00-d71c-11ea-8cd9-5d0a151dd249.png)

Microsoft Edge:
![image](https://user-images.githubusercontent.com/39495762/89458719-5e566d80-d71c-11ea-9f8d-4f258c81538b.png)

**Comment by isaacpearl** [comment]
As a starting point in the codebase - I found that this is coming (at least partially) from style being set to ```style="transform: translateZ(0px); top: 0px; width: 124.109px; position: fixed;"``` on this component (a parent to the sidenav) https://github.com/makerdao/community-portal/blob/c8831ae8ac8e17cf682ca34820c80b517cfef15d/src/modules/layouts/site_layout.js#L43 When the top nav bar is hidden from view.

**Comment by isaacpearl** [comment]
Fixed by #351
