### ISSUE TITLE
Mobile Nav

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#308]
Scrolling doesn't function in the work with us folder, strangely. When you open staging on mobile and there are too many folders to navigate it won't let you move the menu up and down. 

[Here is a vid of the process](https://imgur.com/a/rWqqxwg)
- Click work with us in hamburger
- see folder beyond viewable screen and try to scroll down
- can't scroll down 😭

**Comment by MaximumCrash** [comment]
@twblack88 What phone and browser are you using?

**Comment by twblack88** [comment]
That was chrome on iPhone. I can test again if you would like.

**Comment by MaximumCrash** [comment]
Closed by #441. @twblack88 please test and confirm
