### ISSUE TITLE
Component - CTA 

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#32]
There are a couple of CTA's that comm-dev is set up to use (even though they aren't structured that way in current content). 

- [ ] Box prop with text inside and a linkout. Also in [the explainer](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#702042c58eaf4189ab215082afba9545) Ryan adds a primary color. 
- [x] Clever button placement and [alt text inside of them](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#dc3c44d2d6204c539e347ca302f898e1). I think this might be satisfied by #14 If so we'd just add to the index.mdx pages

Also worth noting, I got confused about the buttons description and CTA's. I missed the color callout which is why this issue wasn't up on Saturday 🤦

**Comment by MaximumCrash** [comment]
The button CTA is a practice more than it is a component. 
I can expect a CC to write this as:

```md
## When

The meetings are **every Thursday** at 4pm UTC (9am PST). We'd love to have you.

<Button>Add to calendar</Button> 
```

**Comment by MaximumCrash** [comment]
This has been completed by #38
