### ISSUE TITLE
Update text treatment for better legibility + increased resemblance to makerdao.com

### ISSUE THREAD

**Issue by shea-fitz** [makerdao/community-portal#321]
[Typography](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=2336%3A0)

Edits to type treatment to improve legibility and more closely align with type treatment at [makerdao.com](https://makerdao.com/en/). Changes are detailed in red text in the frame linked above and include changes to `font-weight` (headers only), `letter-spacing`, and link styling.

![Screen Shot 2020-08-11 at 9 43 07 AM](https://user-images.githubusercontent.com/59940380/89904907-7b28f000-dbb7-11ea-890c-36291852086b.png)

**Comment by amy-jung** [comment]
Shea tried to change in global styling JS style but changes didn't render. 

@isaacpearl are you able to help resolve this issue?

**Comment by twblack88** [comment]
@shea-fitz do you know if you edited the global.css file or the components.js file? I think between those two would be the solution.

**Comment by twblack88** [comment]
leaving this open for @MaximumCrash to give a pass and make sure the different header sizes don't act weird.

**Comment by MaximumCrash** [comment]
Fixed by #427
