### ISSUE TITLE
'hideLanguageSelector:' is causing issues with the header

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community-portal#327]
From what I can tell when 'hideLanguageSelector' is added to the header on the landing pages it removes the section from the navigation. Then if it is removed, the sections remain gone from the navigation requiring a 'yarn clean' and reinstallation of yarn.

**Comment by TomDeMichele** [comment]
```
---
title: Work With Us
description: This is cool!
keywords: "cool, guy, makerdao, ect"
featuredImage: ../images/illus_home.png
hideBreadcrumbs: true
hideLanguageSelector: false
---

<InfoBlock>

![Work with us](/images/illus_work.png)

<Box>

## Work With Us

How you play a part is up to you! And there’s Dai up to be earned.

</Box>

</InfoBlock>

```

**Comment by TomDeMichele** [comment]
Above is an example of the code that caused the issue. Works without the 'hideLanguageSelector' property.

**Comment by TomDeMichele** [comment]
I think it is because I didn't have the header info. This I think fixed it 
```
---
header: true
headerOrder: 1
title: Work With Us
description: This is cool!
keywords: "cool, guy, makerdao, ect"
featuredImage: ../images/illus_home.png
hideBreadcrumbs: true
hideLanguageSelector: false
--- 
```

**Comment by TomDeMichele** [comment]
This did seem to fix it, although I don't know if this was an expected result so I'm leaving it open for now.

**Comment by twblack88** [comment]
yeah that's the proper fix. The field needs to be `false` . Also I believe frontmatter runs only on build so when you change that you need to clean and start again to see it remove.
