### ISSUE TITLE
Testing-  Action pages - Work With Us

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#366]
[Action pages Guide](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) 

Add your name to the `owner` in [content sprint page](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0) to a group of pages. To see action pages only filter the `qa task` column.

#### Work with us/Bounties
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us/onboarding
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
####  Work with us/Translations
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us/Meetups
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us/Hackathons
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us/Governance and risk meetings
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave
#### Work with us/Governance and risk meetings/Take notes
- [x]  phone browser 1 (safari)
- [x]  phone browser 2 (chrome)
- [x]  Desktop chrome
- [x]  Desktop brave

**Comment by eringeorgen** [comment]
Testing

**Comment by eringeorgen** [comment]
Work with us/Translations was not found, completed QA on  Resources/Engineering for Communities/Translations
Work with us/onboarding not found completed QA on resources/onboarding/

**Comment by eringeorgen** [comment]
I am not familiar with Brave, so I completed the Desktop QA of pages using Firefox and Chrome.
