### ISSUE TITLE
Testing - Intro pages/Landing - Learn

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#371]
[Intro Pages Guide](https://www.notion.so/Learn-intro-page-example-Dai-8d6093b9ee5043f2ac9e76094af78446)

- Self-Assign this ticket corresponding to a group of pages
- Add your name to the `owner` in [content sprint page](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0) to a group of pages. To see action pages only filter the `qa task` column.

Test away!

#### Work with us/ Landing Page
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2

#### Funding Landing Page
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2

#### Learn Landing Page
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [x]  Desktop browser 1
- [ ]  Desktop browser 2

#### Learn/Dai
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2

#### Learn/Blockchain
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Learn/Vaults
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Learn/Governance
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
####  Learn/Oracles
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2
#### Learn/MakerDAO
- [ ]  Phone browser 1
- [ ]  Phone browser 2
- [ ]  Desktop browser 1
- [ ]  Desktop browser 2

**Comment by Davidutro** [comment]
Will be checking Learn/Governance

**Comment by andersonmmi** [comment]
Checking Learn Landing Page
