### ISSUE TITLE
Bug - highlighting in SideNav

### ISSUE THREAD

**Issue by andersonmmi** [makerdao/community-portal#400]
**Expected behavior:**

I expect to be able to highlight from the point where I press down to the point where I release the press.

**Observed behavior:**

Highlighting begins at the end of SideNav and ends at the point where I release. In some cases, highlighting gets shifted into the Article text.

**Steps to reproduce:**

This behavior is variable. If you begin the button press close to the text, but not on the clickable area of the link/button, highlighting works as expected. Beginning from above or below the SideNave also behaves as expected.

To reproduce this bug, begin the press from a point further to the left of the links/buttons. Additionally, if you click on a different header link while SideNav text is highlighted, all SideNav text will become highlighted.

**Screenshots:**

![Screen Shot 2020-08-28 at 6 11 47 PM](https://user-images.githubusercontent.com/16314437/91622713-0fd47180-e95e-11ea-9cee-5f41f82a91db.png)

![Screen Shot 2020-08-28 at 6 33 28 PM](https://user-images.githubusercontent.com/16314437/91622717-1367f880-e95e-11ea-9dfd-41c9bcd19862.png)

_In this case, I attempted to highlight SideNav text and highlighting only appeared in Article text_

![Screen Shot 2020-08-28 at 6 33 43 PM](https://user-images.githubusercontent.com/16314437/91622719-1662e900-e95e-11ea-8cd0-8321d99dcf0c.png)

_In this case, highlighting took over SideNav when I clicked the 'Funding' link in HeaderNav_

![Screen Shot 2020-08-28 at 6 39 31 PM](https://user-images.githubusercontent.com/16314437/91622742-34c8e480-e95e-11ea-8c3a-f99b83b1a80f.png)

![Screen Shot 2020-08-28 at 6 39 40 PM](https://user-images.githubusercontent.com/16314437/91622747-3a262f00-e95e-11ea-968f-0e40b4307295.png)

**Comment by twblack88** [comment]
Whoa that's interesting.

**Comment by MaximumCrash** [comment]
@andersonmmi can you give me what device and browser you were using for this bug?

I expect that this may not be able to be fixed since the Sidenav labels are anchor links . Clicking inside of an anchor link and then dragging typically leads to the entire link being dragged off instead of your expectation.

**Comment by MaximumCrash** [comment]
I've labled this won't fix. I tested this in my latest bug bundle and my conclusion is that this is not how links work in modern browsers, they produce a unique drag event like this: . To create a work around to meet this expectation would be a waste of time.

**Comment by MaximumCrash** [comment]
Closed by #441
