### ISSUE TITLE
Scrolling overflow

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#407]
**Describe the bug**
When there are too many pages the sidenav overflows into the footer and won't let you scroll. 

**To Reproduce**
Steps to reproduce the behavior: locally or on staging site you go to 
1. Go to learn/governance
3. Scroll down the sidenav and it gets funky
4. See error vid

**Expected behavior**
sidenav would scroll in its container.

**Screenshots**
[Video](https://youtu.be/C5zgk9FyBoU)

**Desktop (please complete the following information):**
 - OS: MacOS high sierra
 - Browser Chrome 
 - Version 84.0.4147

**Comment by MaximumCrash** [comment]
Fixed by #414
