### ISSUE TITLE
Styling for ticks

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#408]
**Describe the bug**
Tick marks inline with text change the wrapping behavior. 

**To Reproduce**
Steps to reproduce the behavior: on local builds or on the staging site a good testing page is 
1. learn/governance/auditing executive spells
Scroll through teh technical content , the inline code likes to take up space. 
2. work_with_us/content/writing-style-guide
Especially in the do's and don'ts

**Expected behavior**
- New lines wouldn't add extra padding
- If code was wirtten inline the words wouldn't start on a new page.

**Screenshots**
![ smart contract audits](https://user-images.githubusercontent.com/8991325/91765831-7b048a80-eb8e-11ea-8859-24e61dadd9d9.png)
![Styling inline code  writing page](https://user-images.githubusercontent.com/8991325/91765750-56101780-eb8e-11ea-878d-df47a21b1b18.png)
![Installation guide has inline code and words](https://user-images.githubusercontent.com/8991325/91765782-64f6ca00-eb8e-11ea-80f0-4486197c6596.png)

**Desktop (please complete the following information):**
 All

**Smartphone (please complete the following information):**
Didn't test

**Comment by MaximumCrash** [comment]
Fixed by #414
