### ISSUE TITLE
Bug - LanguageSelector effects widths of other components

### ISSUE THREAD

**Issue by andersonmmi** [makerdao/community-portal#411]
**Describe the bug**
When the language selector is not hidden, some components further down the page have their widths reduced by the width of the language selector. This results in text aligned right only extending ~70% of the way to the right.

**To Reproduce**
1. Go to any page where `languageSelectorHidden: false`
2. Scroll below the fold
3. See error

**Expected behavior**
When the language selector is not hidden, components within the Article should appear to inherit the width of the article.

**Screenshots**
_effects highlighted with the pesticide plugin_
![Screen Shot 2020-08-31 at 8 25 05 PM](https://user-images.githubusercontent.com/16314437/91784487-ab691a80-ebc8-11ea-9c29-cc5d48b9f556.png)

_further down the page_
![Screen Shot 2020-08-31 at 8 25 32 PM](https://user-images.githubusercontent.com/16314437/91784506-b623af80-ebc8-11ea-83c8-be80a397eb5e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Browser: chrome
 - Version: 84

**Smartphone (please complete the following information):**
not tested yet

**Additional context**
no additional context yet

**Comment by MaximumCrash** [comment]
@andersonmmi  This is a conflict with the expectations of @shea-fitz. During our development we noticed that because content creators can put anything for the top piece of content we can't predict if the content will be long enough to reach the language selector's position (even more so due to varying display width sizes). My solution was to always set a shorter width for the first 2 elements to make space for the language selector in the event the content wraps and overlaps.

@shea-fitz what would you prefer my direction be in regards to tackling this issue from a design layout perspective?

**Comment by shea-fitz** [comment]
@MaximumCrash @andersonmmi my understanding of the present issue here is that not only is the width of the first two components reduced by the width of the language selector, but so are some elements further down the page even when they are not inline with the language selector themselves. Am I understanding correctly?

My ideal scenario, regardless of whether the language selector is hidden or the content is lower on the page, is that all content only extends 70% of the page width (as the first two elements currently do to accommodate the language selector). 

This would mean that:

- all content is the same width and centered on the page
- content never appears wider on some pages than others
- the language selector basically occupies its own column that is the height of the page, and when the language selector is hidden, this column just acts as a margin
- Desktop pages are essentially 3-column layouts (side nav, page content, language selector each as their own columns)

However, @amy-jung mentioned that some variation of this was already tested, and it made page content feel claustrophobic. That said, I think that problem might be resolved by addressing other legibility issues, including the side nav's right margin, header padding, text size and letter spacing (the latter two which have already been tweaked). As such I would personally encourage the layout I suggest above if it is one of many global layout adjustments. What do others think?

**Comment by MaximumCrash** [comment]
@shea-fitz This sounds good to me. Only thing I'd be concerned about is how we'd want to handle pages like the home page which have neither a sidenav and a language selector. Does this margin rule still take place?

**Comment by MaximumCrash** [comment]
Closed by #441

**Comment by shea-fitz** [comment]
@MaximumCrash Hmm good point. I would leave the home page as is for v1
