### ISSUE TITLE
Divider Doesn't Go All the Way Down to the Footer on Some Resolutions

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community-portal#419]
**Describe the bug**
The divider between the menu and the content doesn’t reach all the way down to the bottom of the screen on larger screens (or when content is reduced in size).

**To Reproduce**
1. Go to any page with a divider, for example, https://community-portal-staging.makerfoundation.com/en/learn/
2. Reduce the size of the font until you see the divider not stretch to the footer.

**Expected behavior**
One would expect the divider to stretch to the footer on all resolutions. Could maybe fix by making the divider line 100% instead of a number of pixels.

**Screenshots**
![Screen Shot 2020-09-01 at 4 11 56 PM](https://user-images.githubusercontent.com/54551507/92042235-a0c89580-ed2e-11ea-9572-afca2d2a3a57.png)

**Desktop (please complete the following information):**
 - OS: OSx
 - Browser Brave
 - Version 1.13.82

**Comment by MaximumCrash** [comment]
Closed by #441
