### ISSUE TITLE
Chocolate boxes Improvements

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#425]
**Describe the bug**
Chocolate boxes don't like even numbers and they don't like aligning.

**To Reproduce**

Funding homepage is the best place to look at this. @TomDeMichele will attach a comment.

**Expected behavior**
Content creators feel that content should wrap to 2 box with flex. but even numbers of boxes don't align and they seem to dislike being centered. On top of that the CSS grid styles need a little encouragement. 

**Screenshots**

**Desktop (please complete the following information):**
 - MAc
 - Brave
 - Newest

**Additional context**

**Comment by MaximumCrash** [comment]
@twblack88 @TomDeMichele After doing some snooping I noticed 2 things. 

1. The mdx for the funding page with regards to chocolate boxes was incorrect. There were 2 `<Chocolate>` components with 2 box child components. The recommended usage for each chocolate is 1 chocolate component with individual box children. 

2. The Chocolate component as designed by @shea-fitz is specced for 3 elements per column. @shea-fitz  to meet the needs of this task for CC's I'll be changing them to meet that expectation for 1 element, 2 elements, 4 elements, ect.

**Comment by MaximumCrash** [comment]
Fixed by #427
