### ISSUE TITLE
New component to "automate" text indentation below headers.

### ISSUE THREAD

**Issue by HaydenSander** [makerdao/community-portal#426]
**Is your feature request related to a problem? Please describe.**

I find that large amounts of text all aligned left can be daunting to follow. 

**Describe the solution you'd like**

While a solution would be to "shorten the contents" so it doesn't overwhelm the reader as much this can not always be accomplishable and such a method that I came up with may translate to a new component. 

To put it simply this component would indent based on either detecting what Header size is being wrapped and indent accordingly based on a similar ruleset to what I suggest below (Screenshot examples) OR would be a simple "Props" option for us the editor to change on our own. This new component could be named "HeaderBox", "BoxIndent" or "HeaderIndent", as a few suggestions.

**Describe alternatives you've considered**

I explain both variants and the 3rd solution making content less lengthy does not always suite the situation.

**Screenshots and Additional context**

Here are the 3 variations of the new component that I see working.

1.  Wrap Header and/or content in a new component, it indents content X amount. This would be applied with the same amount of indenting no matter what the header size or content wrapped. 

2. We wrap content and manually select via a "Props" option the Header size in use. This Indenting would scale properly from mobile to desktop.

![image](https://user-images.githubusercontent.com/39495762/92145511-2ef35900-edcd-11ea-8b34-ac37b102b06e.png)

**IGNORE THE LAST SUGGESTION**
I evaluated the usecases of this kind of "automated detection" and realized I have many situations where this exact ruleset is not used. I left it in case it gave insight into new ideas.

3. Detect what Header size is being wrapped and indent accordingly based on the predetermined component logic.

So while going through the process of determining a set of "ground rules" I would apply widely I came to the conclusion of using a "paddingX" amount equal to the Header size. I will show you an example of this below. 

![image](https://user-images.githubusercontent.com/39495762/92146042-f6a04a80-edcd-11ea-9ad0-1b1ea0fd47a0.png)
Note: I treated the Bolded text as an H5 since we don't have one and it is near what the size of our H5 would be I imagine. 

Which ends up giving us this kind of an outcome:

 ![image](https://user-images.githubusercontent.com/39495762/92146127-1cc5ea80-edce-11ea-8cc0-5fe0268303ba.png)

Alright, now that hopefully you can see how I came to some kind of a logic determination this or a similar ruleset could be built into the component and acted on automatically unless disabled via one of the "Props" options.

**Comment by MaximumCrash** [comment]
Closed by #441
