### ISSUE TITLE
Mobile Menu Dropdown Doesn't Expand When Down Arrow Clicked

### ISSUE THREAD

**Issue by eringeorgen** [makerdao/community-portal#436]
**Describe the bug**
Issue occurs mobile browsers, when attempting to expand a menu item that includes a dropdown arrow. Instead of opening the dropdown menu, the main mobile menu closes and the user is navigated the the parent page. At that point, the user could re-open the main navigation menu and the dropdown they clicked is open. If the user needs to navigate to a specific page that is 2 dropdown arrows into the menu, the user must re-open the main navigation menu and wait for the parent page for that dropdown to load both times.

**To Reproduce**
1. Go to any page on any mobile browser
2. Click on the main navigation menu
3. Attempt to Navigate to: Work With Us/Governance and Risk Meetings/
Take Notes/Governance Call Notes Template
4. See error x 4

**Expected behavior**
The user should be able to open the internal dropdown menus within the main navigation menu simply by clicking the down arrow without being navigated to the parent pages and the mobile menu closing first.

**Smartphone (please complete the following information):**
 - Device: iPhone SE, iPhone Xs, (and also my MacBook Air when the browser window in narrowed)
 - Browser: All

**Comment by MaximumCrash** [comment]
Not a bug, but is working as "was" inteneded. This is part of changes I'm making to the sidenav refactor #429
