### ISSUE TITLE
Multiple Columns in Callouts Aren't Responsive

### ISSUE THREAD

**Issue by eringeorgen** [makerdao/community-portal#458]
**Describe the bug**
Issue occurs on mobile devices and narrow browser windows when there are multiple columns of content within a Callout. The issue is more pronounced when the type size is increased and causes the columns of content break out of the Callout frame.

**To Reproduce**
1. Go to [Work with Us](https://community-portal-staging.makerfoundation.com/en/work_with_us/) on a mobile device or desktop.
2. Scroll down to the first Callout 
3. See 2 columns of content that breaks the frame of the Callout

**Expected behavior**
The multiple columns should be responsive to the browser window as it narrows, reducing to a single column for mobile devices.

**Screenshots**
Mobile Browsers (Regular type vs enlarged type):
Safari
![IMG_4640](https://user-images.githubusercontent.com/70353047/93282239-cae47380-f782-11ea-8b90-6785aae8d8b4.PNG)
![IMG_4643](https://user-images.githubusercontent.com/70353047/93282255-d768cc00-f782-11ea-8e4f-5565c1481722.PNG)
Chrome
![IMG_4641](https://user-images.githubusercontent.com/70353047/93282299-ee0f2300-f782-11ea-80a6-3d0846b248e5.PNG)
![IMG_4642](https://user-images.githubusercontent.com/70353047/93282303-f49d9a80-f782-11ea-8f8e-76aabd4c2810.PNG)

Desktop
Chrome
<img width="1049" alt="Screen Shot 2020-09-15 at 6 22 07 PM" src="https://user-images.githubusercontent.com/70353047/93282471-578f3180-f783-11ea-857c-9ba723a1adc6.png">
<img width="1061" alt="Screen Shot 2020-09-15 at 6 22 30 PM" src="https://user-images.githubusercontent.com/70353047/93282476-59f18b80-f783-11ea-8412-7f0470805a3d.png">
Firefox
<img width="794" alt="Screen Shot 2020-09-15 at 6 20 52 PM" src="https://user-images.githubusercontent.com/70353047/93282488-5f4ed600-f783-11ea-8045-d19cbf94fc5c.png">
<img width="788" alt="Screen Shot 2020-09-15 at 6 21 25 PM" src="https://user-images.githubusercontent.com/70353047/93282498-62e25d00-f783-11ea-9e74-df2683121338.png">

**Desktop (please complete the following information):**
 - OS: Catalina Version 10.15.6
 - Browser: Chrome, Frirefox

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - Browser: Chrome, Safari

**Comment by MaximumCrash** [comment]
~@shea-fitz making this 1 column on mobile.~

This is already 1 column on mobile. Zooming in causing unexpected views. wontfix

**Comment by twblack88** [comment]
We ended up fixing this after all!
