### ISSUE TITLE
"Suggested Reading" Content Columns Aren't Responsive

### ISSUE THREAD

**Issue by eringeorgen** [makerdao/community-portal#460]
**Describe the bug**
The issue is seen on the "Take Notes" page under the "Suggested Reading" heading. The content below that heading is in three columns that are not reducing to single column on mobile devices or narrowed browser windows.

**To Reproduce**
1. Go to [work_with_us/governance_and_risk_meetings/take-notes](https://community-portal-staging.makerfoundation.com/en/work_with_us/governance_and_risk_meetings/take-notes) on a mobile device or on a desktop with the browser window's width minimized.
2. Scroll down to "Suggested Reading"
3. See the content organized into three columns (does not appear to be a Column from the Content Pallet). Increase the type size to make the issue more pronounced on desktop.

**Expected behavior**
Multicolumn layouts should be responsive and reduce to a single column on narrow browser windows and mobile devices.

**Screenshots**
Mobile Device:
Chrome (default and increased type size)
![IMG_4658](https://user-images.githubusercontent.com/70353047/93295357-ae0b6880-f7a1-11ea-9b96-1e970b66f915.PNG)
![IMG_4659](https://user-images.githubusercontent.com/70353047/93295363-b06dc280-f7a1-11ea-8107-7d279e038ed6.PNG)

Safari
![IMG_4661](https://user-images.githubusercontent.com/70353047/93295387-c24f6580-f7a1-11ea-985c-11281a12dc26.PNG)

Desktop, narrowed browser windows (default vs enlarged type)
Firefox
<img width="468" alt="Screen Shot 2020-09-15 at 9 59 59 PM" src="https://user-images.githubusercontent.com/70353047/93295631-515c7d80-f7a2-11ea-880e-de17916d5560.png">
<img width="470" alt="Screen Shot 2020-09-15 at 10 00 32 PM" src="https://user-images.githubusercontent.com/70353047/93295492-f32f9a80-f7a1-11ea-9cbc-f257cae1c20b.png">
Chrome
<img width="515" alt="Screen Shot 2020-09-15 at 10 00 47 PM" src="https://user-images.githubusercontent.com/70353047/93295512-06426a80-f7a2-11ea-8569-545ba1a4bba8.png">
<img width="510" alt="Screen Shot 2020-09-15 at 10 28 03 PM" src="https://user-images.githubusercontent.com/70353047/93295818-c62fb780-f7a2-11ea-8997-4daceb897f68.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.6
 - Browsers: Firefox, Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - Browsers: Safari, Chrome

**Comment by MaximumCrash** [comment]
@shea-fitz I will be making these 1 column on mobile.

**Comment by MaximumCrash** [comment]
Closed by #474
