### ISSUE TITLE
List Component Bug Squashing

### ISSUE THREAD

**Issue by andytudhope** [makerdao/community-portal#54]
The `<List />` Component is amazing. However, I have been able to find one bug with it in writing the documentation for content creators. Thus bug comes in two parts, one annoying, the other breaking.

### Annoying

If I write some mdx like this:

```
<List>

   - Header text
       - <Box> 
           
        ### More complicated MD ... 
           
        </Box>

</List>
```

The md in the box is not rendered correctly - it appears as written, rather than an h3.

### Breaking

If I then add a new line between the `Header text` and the `- <Box>` things break badly:

```
<List>

   - Header text

       - <Box> 
           
        ### More complicated MD ... 
           
        </Box>

</List>
```

![Screenshot from 2020-06-25 20-03-56](https://user-images.githubusercontent.com/13001517/85775619-3a1c6f80-b720-11ea-82bc-a444b645e367.png)

**Comment by MaximumCrash** [comment]
@andytudhope Lists are now much more stable. This has been closed by #85
