### ISSUE TITLE
Inline Code should stand out more

### ISSUE THREAD

**Issue by andytudhope** [makerdao/community-portal#61]
Currently, when I use short-hand inline code to indicate a technical file name, component or function in a paragraph of text, `like this`, the result is not as prominent as it should be. This is not a bug, but my opinion.

The fontSize is smaller, and the padding is less than normal text, so it ends up looking cramped, and it's difficult to distinguish between code and normal text. I would want this to stand out, i.e.

1. Be in a slightly different color
2. Have extra padding, not less
3. Maybe have a different background color
4. Maybe have a different fontWeight
5. Have the same fontSize as our text.

**Comment by MaximumCrash** [comment]
Closed by #88
