### ISSUE TITLE
404 Pages

### ISSUE THREAD

**Issue by MaximumCrash** [makerdao/community-portal#69]
Shea has passed off the initial designs for 404 pages. [Here](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev)

Images, if you don't have access
![Screen Shot 2020-06-30 at 10 00 04 AM](https://user-images.githubusercontent.com/9157341/86135242-89fc8d00-bab8-11ea-9b08-83a176b6baca.png)
![Screen Shot 2020-06-30 at 10 00 10 AM](https://user-images.githubusercontent.com/9157341/86135245-8b2dba00-bab8-11ea-92ac-ee7f2ee15d53.png)

Internally 404 pages will be a config file at the top level as (/[LOCALE]/404.mdx). The content we see on the left is editable except for the button/link ("Go Back" and "Report a Bug") which will be translatable in the UI.json for their respective locale. 

The reason for this line of thinking is that we want to offer translateable content (that would be written by a content creator), but we don't want to give them too much control. It's a 404 page, it only serves one purpose. 

Thus, 404.mdx content is expected to be pulled down into the 404.js page in the same fashion header/footer mdx content is fetched using a static query. We then render the correct content depending on the current locale. 

**NOTE: 404 pages MUST fallback to the default locale's 404 page if the current locale does not have one. If NO locales have a 404 page, have a fallback that renders The images above, but inlined.**

Acceptance Criteria: 

- A 404.mdx file located at the top level locale of our content directory (ie. content/en/404.mdx)
       - 1 404.mdx page for English (as the default locale fallback) 
       - 1 404.mdx page for French (as a test for current locale translateable 404 pages)
- A 404.js file in src/pages/ (**should already exist**) that pulls in all 404.mdx pages from locale folders and renders the appropriate one for our current locale. 
     - If the current locale doesn't contain a 404.mdx file, render the default locale 404.mdx. 
     - If the default locale doesn't contain a 404.mdx file, render the 404 page inline. 
- I should be able to go the 404 page by typing a non-existing page and see the appropriate 404 page for my current locale. (**404s are NOT going to have a locale url like en/404.mdx**)
- The Go Back link should NOT be in the mdx file and instead is inlined with it's copy rendered using the "t" function. Clicking it should return me to my previous page. **Add the string to the locales UI.json with a consistent key, ~then update the graphql query for the locale json in PageContext~, THEN provide it like ```t("YOUR KEY")```. <-- If you need help with this let me know. 
- The Report a Bug button should NOT be in the mdx file and is also inlined next Go Back. It should also be translated using a t function as well. Clicking this button should take me to this link --> https://github.com/makerdao/community-portal/issues 
- As the specs show, there's no image currently and you don't need to make blank square, but please prove that the layout supports adding an image there in the future. 
- Do NOT do mobile styles. I will do them in one full sweep. 

**NOTE: During development gatsby will render their own 404 page. Make sure to click the "Preview custom 404 page" or just run ```yarn build``` and then ```yarn serve``` to see it live.**
![Screen Shot 2020-07-01 at 5 58 28 PM](https://user-images.githubusercontent.com/9157341/86295504-c4ebe700-bbc4-11ea-9a74-d58a0135aca2.png)

**BE AWARE: When testing the 404 page during development you will see the header and footer rendered twice. This is not a production issue, but you should test it using yarn build + yarn serve to see the true results. I recommend using a test.mdx page to test out your logic and display format.**

**Comment by isaacpearl** [comment]
- [x] ```404.mdx``` files for each locale at top level
    - [x] English
    - [x] French
    - [x] Spanish
- [x] ```content/en/404.mdx``` as default for locales with no translated 404 page
- [x] ```404.js```
    - [x] If the current locale doesn't contain a 404.mdx file, render the default locale 404.mdx.
    - [x] If the If the default locale doesn't contain a 404.mdx file, render the 404 page inline.
    - [x] Go Back link is inline with copy rendered by the ```t()``` function
    - [x] Report a Bug button inlined next to Go Back with ```t()``` (go to https://github.com/makerdao/community-portal/issues)
    - [x] Show that the layout supports adding an image in the future

**Comment by MaximumCrash** [comment]
Updated AC to remove "then update the graphql query for the locale json in PageContext" since the importing of UI.json has been radically simplified.

**Comment by MaximumCrash** [comment]
This has been completed by #149
