### ISSUE TITLE
Google Analytics - The Great Tracking Optimization

### ISSUE THREAD

**Issue by MaximumCrash** [makerdao/community-portal#87]
While we have basic SEO in place, it's time for us to begin implementing Google Analytics into our app in the places that need it. 

Tagging @twblack88 for this one. 

Please list out what we'd want to track and any features (like A/B testing) we'd want integrated below:

**Comment by twblack88** [comment]
First thoughts without notes, just a data dump:
- Action pages, especially if they result in a button
- button trigger's result in a goal page (maybe needs a design spec)
- even better button triggers redirect and then trigger a GA tag
- probs a GA tag (frontmatter or component) element as a result which would then open more cans of worms

**Comment by MaximumCrash** [comment]
@twblack88 Because we're using Google Analytics, I'm going to need a privacy policy and cookie banner details for the site. We're going to need to be GDPR compliant and ensure we've got all the bells and whistles to protect our users. 

~Will we use MakerDao's existing privacy policy or write our own?~
I will write tickets for these. They are a must have.

**Comment by MaximumCrash** [comment]
Google Analytics is forever a work in progress. My work on #95 closes this issue for the time being. 
I recommend making new issues for those specific cases.
