### ISSUE TITLE
Component- Page heading

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#9]
[Ryan's explanation page]( https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#8714e287f8c94c2baf0afb5f37b3eb85)

Figma template not needed.

### Description
**Use this component to label the page and provide a high-level summary of what the page is about.** 

Ensure the title aligns with links in the navigation. It should match what the user has clicked on.

**Comment by MaximumCrash** [comment]
Already implemented in MDX in the form of an H1

# Like this one
