### ISSUE TITLE
Privacy Policy and/or Cookie Banner

### ISSUE THREAD

**Issue by MaximumCrash** [makerdao/community-portal#96]
Because our site uses Google Analytics we need to tell our users we're collecting their data. This is not only best practice, but the best thing for our users. We want data, but we want to do it the right way.

With that in mind we're going to need a privacy policy and make use of a cookie banner to let users know we are collecting data. (At the moment users can also opt out of data collection, there's a button in the footer, but we should talk about if this is something we want to offer.)

Tagging @twblack88 for this one. Let's start this conversation.

**Comment by twblack88** [comment]
We'll need a design mock for this correct?

+1 for opt out button everyone loves privacy if they have the chance.

**Comment by MaximumCrash** [comment]
@twblack88 Yeah we would need one for both the privacy policy and cookie banner. Thought I don't think it would be hard to design. We just need the copy for the banner written. The rest is a breeze.

**Comment by amy-jung** [comment]
@ghettodev and I were discussing and it'd be helpful to know:

What exactly are the things we're collecting?

**Comment by MaximumCrash** [comment]
@amy-jung We are currently tracking:

- Internal Links (ie. going from homepage to work_with_us)
- Outbound Links (ie. clicking a link that takes you away from the site)
- Clicking a Search Result to an internal link page
- Using the Language Selector to change a language on a content page. 

By default I have user anonomize set to true so no one user can be identified, we have respectDNT set to true for if users have "Do Not Track" enabled in their browsers, and we automatically get user possible location (this is something built into Google Analytics itself).

**Comment by amy-jung** [comment]
Sorry, we were meant to bring this up last week. I'll bring it up in today's Wednesday call.

**Comment by MaximumCrash** [comment]
@twblack88 What's the final call on this? Are we not moving forward with google analytics for launch?

**Comment by twblack88** [comment]
I believe we're continuing with current configuration pending privacy policy. We'll revisit the advanced stuff as the marketing push (CDIPs) goes out.

**Comment by amy-jung** [comment]
As is, it's currently about 20 pages long 🤪  so its going through review. If you have comments pls put it in the doc
